package com.adonnis.app.reminder

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import com.adonnis.app.data.local.entity.ReminderEntity

/**
 * Schedules and cancels exact alarm reminders using Android's AlarmManager.
 * Handles Android 14+ (API 34+) exact alarm permission requirements.
 */
class ReminderScheduler(private val context: Context) {

    private val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as? AlarmManager

    /**
     * Schedule a reminder. Uses [AlarmManager.setExactAndAllowWhileIdle]
     * for precise delivery. On Android 14+ falls back to [setExact] if
     * exact alarm permission is not granted.
     */
    fun schedule(reminder: ReminderEntity) {
        val alarmManager = alarmManager ?: return

        // Nothing to schedule for past or completed reminders — just clean up.
        if (reminder.dateTime <= System.currentTimeMillis() || reminder.isCompleted) {
            cancelById(reminder.id)
            return
        }

        // Cancel any existing alarm for this reminder FIRST (by ID), then
        // create a FRESH PendingIntent. Creating the PendingIntent before
        // cancelling would cancel the very PendingIntent we then schedule —
        // and a cancelled PendingIntent never delivers. This ordering bug
        // is why reminders silently never fired.
        cancelById(reminder.id)
        val pendingIntent = createPendingIntent(reminder)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // Android 12+: check if exact alarm permission is available
            if (alarmManager.canScheduleExactAlarms()) {
                alarmManager.setExactAndAllowWhileIdle(
                    AlarmManager.RTC_WAKEUP,
                    reminder.dateTime,
                    pendingIntent
                )
            } else {
                alarmManager.set(
                    AlarmManager.RTC_WAKEUP,
                    reminder.dateTime,
                    pendingIntent
                )
            }
        } else {
            alarmManager.setExactAndAllowWhileIdle(
                AlarmManager.RTC_WAKEUP,
                reminder.dateTime,
                pendingIntent
            )
        }
    }

    /** Cancel a scheduled reminder by its entity */
    fun cancel(reminder: ReminderEntity) {
        val alarmManager = alarmManager ?: return
        val pendingIntent = createPendingIntent(reminder)
        alarmManager.cancel(pendingIntent)
        pendingIntent.cancel()
    }

    /** Cancel a reminder by its ID */
    fun cancelById(reminderId: Long) {
        val alarmManager = alarmManager ?: return
        val intent = Intent(context, ReminderReceiver::class.java).apply {
            // Must match createPendingIntent's action — PendingIntent identity
            // uses Intent.filterEquals() which INCLUDES the action. Without it,
            // this PI never matches the scheduled one and the alarm isn't
            // cancelled (e.g. a completed reminder would still fire later).
            action = ACTION_REMINDER_TRIGGERED
            putExtra(EXTRA_REMINDER_ID, reminderId)
        }
        val pendingIntent = PendingIntent.getBroadcast(
            context,
            reminderId.toInt(),
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
        alarmManager.cancel(pendingIntent)
        pendingIntent.cancel()
    }

    /** Reschedule all active reminders (used after boot) */
    fun rescheduleAll(reminders: List<ReminderEntity>) {
        // Cancel all existing alarms first
        for (reminder in reminders) {
            cancelById(reminder.id)
        }
        // Re-schedule only future, non-completed ones
        val now = System.currentTimeMillis()
        for (reminder in reminders) {
            if (!reminder.isCompleted && reminder.dateTime > now) {
                schedule(reminder)
            }
        }
    }

    /** Create a PendingIntent that fires the ReminderReceiver */
    private fun createPendingIntent(reminder: ReminderEntity): PendingIntent {
        val intent = Intent(context, ReminderReceiver::class.java).apply {
            putExtra(EXTRA_REMINDER_ID, reminder.id)
            putExtra(EXTRA_REMINDER_TITLE, reminder.title)
            putExtra(EXTRA_REMINDER_DESC, reminder.description ?: "")
            putExtra(EXTRA_REMINDER_IS_AUTO, reminder.isAutoGenerated)
            action = ACTION_REMINDER_TRIGGERED
        }
        return PendingIntent.getBroadcast(
            context,
            reminder.id.toInt(),
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
    }

    companion object {
        const val EXTRA_REMINDER_ID = "extra_reminder_id"
        const val EXTRA_REMINDER_TITLE = "extra_reminder_title"
        const val EXTRA_REMINDER_DESC = "extra_reminder_desc"
        const val EXTRA_REMINDER_IS_AUTO = "extra_reminder_is_auto"
        const val ACTION_REMINDER_TRIGGERED = "com.adonnis.app.ACTION_REMINDER_TRIGGERED"
        const val ACTION_REMINDER_DONE = "com.adonnis.app.ACTION_REMINDER_DONE"
        const val ACTION_REMINDER_SNOOZE = "com.adonnis.app.ACTION_REMINDER_SNOOZE"
    }
}
