package com.adonnis.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Stores a wake-up alarm configuration including the math challenge difficulty.
 * The actual math questions are generated by the AI when the alarm triggers.
 */
@Entity(tableName = "alarms")
data class AlarmEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "label")
    val label: String = "Wake Up!",

    @ColumnInfo(name = "hour")
    val hour: Int,

    @ColumnInfo(name = "minute")
    val minute: Int,

    /** JSON array of day-of-week indices (0=Sunday, 6=Saturday) */
    @ColumnInfo(name = "days_of_week_json")
    val daysOfWeekJson: String = "[1,2,3,4,5]", // Weekdays by default

    @ColumnInfo(name = "is_enabled")
    val isEnabled: Boolean = true,

    /** "easy", "medium", or "hard" */
    @ColumnInfo(name = "math_difficulty")
    val mathDifficulty: String = "medium",

    /** JSON array of math questions generated by the AI (cached per alarm trigger) */
    @ColumnInfo(name = "math_questions_json")
    val mathQuestionsJson: String? = null,

    /** "strict" = can't dismiss until solved, "normal" = can snooze repeatedly */
    @ColumnInfo(name = "mode")
    val mode: String = "strict",

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
