package com.adonnis.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Stores a daily plan generated by the AI for the 3-day rolling window.
 * One row per day (always 3 active rows: today, tomorrow, day after).
 */
@Entity(
    tableName = "plans",
    indices = [Index(value = ["date"], unique = true)]
)
data class PlanEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    /** ISO date string, e.g. "2026-07-30" */
    @ColumnInfo(name = "date")
    val date: String,

    /** 0 = today, 1 = tomorrow, 2 = day after tomorrow */
    @ColumnInfo(name = "day_relative")
    val dayRelative: Int,

    /** Full plan as JSON from the AI — array of time blocks */
    @ColumnInfo(name = "plan_json")
    val planJson: String,

    /** Detail level: "detailed", "moderate", "overview" */
    @ColumnInfo(name = "detail_level")
    val detailLevel: String = "moderate",

    @ColumnInfo(name = "generated_at")
    val generatedAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "updated_at")
    val updatedAt: Long = System.currentTimeMillis()
)
