package com.adonnis.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Stores a single reminder — either user-created or AI-auto-generated.
 * Can be a one-time or repeating reminder.
 */
@Entity(tableName = "reminders")
data class ReminderEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "description")
    val description: String? = null,

    /** Epoch millis for the reminder time */
    @ColumnInfo(name = "date_time")
    val dateTime: Long,

    @ColumnInfo(name = "is_completed")
    val isCompleted: Boolean = false,

    /** True if the AI auto-generated this reminder from plans */
    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = false,

    /** Repeat interval in millis — 0 means no repeat */
    @ColumnInfo(name = "repeat_interval_millis")
    val repeatIntervalMillis: Long = 0L,

    /** Reference to the plan block that generated this (if auto-generated) */
    @ColumnInfo(name = "source_plan_date")
    val sourcePlanDate: String? = null,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis()
)
